#!/bin/bash

search()
{
	case $1 in
		"-ff" | "--findfile")
		#find file in directory
		case $4 in
			"-r" | "--regex")
			sudo find $3 -type f -name $2 | grep $5
			;;
			*)
			sudo find $3 -type f -name $2
			;;
		esac
		;;

		"-fd" | "--finddir")
		#find directory in directory
		case $4 in
                        "-r" | "--regex")
                        sudo find $3 -type d -name $2 | grep $5
                        ;;
                        *)
                        sudo find $3 -type d -name $2
                        ;;
                esac
		;;

		"-l" | "--locate")
		#locate file or directory
		sudo updatedb
		case $3 in
			"-r" | "--regex")
			sudo locate $2 | grep $4
			;;
			*)
			sudo locate $2
			;;
		esac
		;;

		"-w" | "--which")
		case $3 in
			"-r" | "--regex")
			which $2 | grep $4
			;;
			*)
			which $2
			;;
		esac
		;;

		"-ws" | "--whereis")
		case $3 in
			"-r" | "--regex")
                        whereis $2 | grep $4
                        ;;
			*)
			whereis $2
			;;
		esac
		;;

		"-h" | "--help")
		echo "The search command is a convienent way of using many search commands well only remembering one."
		echo "The --help page also lists the commands search wraps as a quick refernce so you can use those"
		echo "commands at their full power"
		echo "-----------------------------------------------------------------------------------------------"
		echo "Commands and Options:"
		echo "find:"
		echo "	-ff, --findfile: "
		echo "			Uses find command to find files,"
		echo "			ex: search -ff <file> <dir tree to search>"
		echo "	-fd, --finddir: "
		echo "			Uses find command to find directories,"
		echo "			ex: search -fd <dir> <dir tree to search>"
		echo "locate:"
		echo "	-l, --locate: "
		echo "			runs updatedb command and uses locate command to find files or directories"
		echo "			ex: search -l <file/dir>"
		echo "which:"
		echo "	-w, --which:"
		echo "			Uses which command to find programs and applications"
		echo "			ex: which <file>"
		echo "whereis:"
		echo "	-ws, --whereis: "
		echo "			Uses whereis command to find programs, source files and man files in a broad search range"
		echo "			ex: whereis <file>"
		echo "grep:"
		echo "	-r, --regex: "
		echo "			refine any search by adding grep as a final parameter"
		echo "			ex: search -l <file> -r <keyword>"
		;;

		*)
		echo "Type search -h or search --help for options and examples"
		;;
	esac

}

envctl()
{
	if [ $1 = "-c" ] || [ $1 = "--create" ]
	then
		python3 -m venv $2
		echo $(pwd)/$2 >> ~/text_files/my_environments.txt
	elif [ $1 = "-a" ] || [ $1 = "--activate" ]
	then
		source ./$2/bin/activate
	else
		echo "The envctl (environment controller) speeds up and simplifies the creation and use of a python3 venv"
		echo "Options: "
		echo "	-c, --create: "
		echo "			Creates a python3 virtual environment in present working directory"
		echo "			ex: envctl -c <env_name>"
		echo "	-a, --activate: "
		echo "			Activates an environment quickly by name"
		echo "			ex: envctl -a <env_name>"
		echo "deactivation of an environment is a function of the venv module itself,"
		echo "in the directory you activated your environment you deactivate it by simply tyiping deactivate"
		echo "			ex: deactivate"
	fi
}
